### ISSUE TITLE
When posting invalid json data the API is exposing too much information

### ISSUE THREAD

**Issue by pjanuario** [micro-toolkit/api-generator-js#114]
When the user sends a invalid json data, the API is returning a stack trace:

`SyntaxError: Unexpected token ;<br> &nbsp; &nbsp;at Object.parse (native)<br> &nbsp; &nbsp;at parse (/opt/app/node_modules/micro-toolkit-api-generators/node_modules/body-parser/lib/types/json.js:88:17)<br> &nbsp; &nbsp;at /opt/app/node_modules/micro-toolkit-api-generators/node_modules/body-parser/lib/read.js:116:18<br> &nbsp; &nbsp;at invokeCallback (/opt/app/node_modules/micro-toolkit-api-generators/node_modules/body-parser/node_modules/raw-body/index.js:262:16)<br> &nbsp; &nbsp;at done (/opt/app/node_modules/micro-toolkit-api-generators/node_modules/body-parser/node_modules/raw-body/index.js:251:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (/opt/app/node_modules/micro-toolkit-api-generators/node_modules/body-parser/node_modules/raw-body/index.js:307:7)<br> &nbsp; &nbsp;at emitNone (events.js:67:13)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:166:7)<br> &nbsp; &nbsp;at endReadableNT (_stream_readable.js:905:12)<br> &nbsp; &nbsp;at nextTickCallbackWith2Args (node.js:441:9)`

**Comment by pjanuario** [comment]
Fixed by https://github.com/micro-toolkit/api-generator-js/pull/123
